apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: testing
  source:
    repoURL: https://github.com/JoshLee0915/k8BlueGreenTesting.git
    targetRevision: HEAD
    path: argo-rollouts/env/local-dev