apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-api-bg
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: testing
  source:
    repoURL: https://github.com/JoshLee0915/k8BlueGreenTesting.git
    targetRevision: HEAD
    path: test-api-deploy/env/local-dev-bg